@startuml

title Home Page

boundary Page as p
control App as a
control AWS as s
database Content as c

... Initialize Application ...
p -> a : init()
a --> p : render
... Initialize User ...
a -> s : Cognito auth user
s --> a : user info
s --> a : dataset
a --> p : render
... Fetch Content ...
a -> c : getContentFor(home)
c --> a : content
a --> p : render

@enduml
